import { useState } from 'react';
import { Plus, Save } from 'lucide-react';
import { leaveApi } from './leaveApi';
import { Notice, Directory, field, button, secondary, label, useLoad } from './leaveUi';
export function SettingsForm({ meta, saved }) {
  const [types, setTypes] = useState(meta.types), [reviewers, setReviewers] = useState(meta.reviewers || []), [allowPast, setPast] = useState(meta.allowPast);
  const [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const update = (index, name, value) => setTypes(types.map((t, i) => i === index ? { ...t, [name]: value } : t));
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const r = await leaveApi('/settings', { method: 'PUT', body: { version: meta.version, types, reviewers, allowPast, reason } }); saved(r.message); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><fieldset disabled={busy} className="space-y-6">
    <div><h2 className="text-lg font-semibold text-slate-900">Company leave policy</h2><p className="mt-1 text-sm text-slate-500">Create leave types and select who receives approval requests. Balances are allocated separately.</p></div>
    <div className="space-y-3">{types.map((t, i) => <div key={t._id || `new-${i}`} className="flex flex-wrap items-center gap-4 rounded-xl bg-slate-50 p-4"><input aria-label="Leave type name" required minLength={2} maxLength={80} className={`${field} sm:!w-64`} placeholder="e.g. Casual leave" value={t.name} onChange={e => update(i, 'name', e.target.value)}/>{[['paid', 'Paid'], ['halfDay', 'Half-day allowed'], ['active', 'Active']].map(([key, title]) => <label key={key} className="flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={t[key]} disabled={key === 'paid' && Boolean(t._id)} onChange={e => update(i, key, e.target.checked)}/>{title}</label>)}{!t._id && <button type="button" className={secondary} onClick={() => setTypes(types.filter((_, n) => n !== i))}>Remove</button>}</div>)}</div>
    <button type="button" className={secondary} disabled={types.length >= 30} onClick={() => setTypes([...types, { name: '', paid: true, halfDay: true, active: true }])}><Plus size={16}/> Add leave type</button>
    <div className="grid gap-6 lg:grid-cols-2"><div className="space-y-3"><h3 className="text-sm font-semibold text-slate-800">Approval recipients</h3><p className="text-xs text-slate-500">Active users with Approve leaves permission. Applicant cannot approve their own request. Configure at least two approvers if approvers also apply for leave.</p><Directory reviewersOnly multiple selected={reviewers} onChange={setReviewers}/><button type="button" className={secondary} onClick={() => setReviewers([])}>Clear approvers</button></div><div className="space-y-5"><label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={allowPast} onChange={e => setPast(e.target.checked)}/>Allow backdated applications</label><label className={label}>Reason for policy change<textarea required minLength={3} maxLength={1000} className={field} rows={4} value={reason} onChange={e => setReason(e.target.value)}/></label><p className="text-xs leading-5 text-slate-500">Existing requests retain their original dates, charged days and paid/unpaid classification. Policy changes apply to new applications.</p></div></div>
    </fieldset><Notice error>{error}</Notice><button className={button} disabled={busy}><Save size={16}/>{busy ? 'Saving…' : 'Save policy'}</button>
  </form>;
}
export function Allocations({ year, refresh, saved }) {
  const [selected, setSelected] = useState([]), [typeId, setType] = useState(''), [units, setUnits] = useState(''), [reason, setReason] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const state = useLoad(selected[0] ? `/balance?year=${year}&employee=${selected[0]}` : null, refresh);
  async function submit(e) { e.preventDefault(); if (!state.data) return; setBusy(true); setError(''); try { const r = await leaveApi('/allocation', { method: 'PUT', body: { employee: selected[0], year, typeId, units: Number(units), reason, version: state.data.version } }); setReason(''); setUnits(''); saved(r.message); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="grid gap-6 rounded-2xl border border-slate-200 bg-white p-5 lg:grid-cols-2"><fieldset disabled={busy}><h2 className="mb-3 text-lg font-semibold text-slate-900">Allocate paid leave · {year}</h2><Directory selected={selected} onChange={v => { setSelected(v); setType(''); setUnits(''); }}/></fieldset><fieldset disabled={busy || state.loading || !state.data} className="space-y-4"><p className="text-sm text-slate-500">Set the total annual entitlement—not additional days. Every adjustment is recorded with your reason.</p><label className={label}>Paid leave type<select required className={field} value={typeId} onChange={e => { setType(e.target.value); setUnits(''); }}><option value="">Select type</option>{state.data?.balances?.filter(t => t.paid).map(t => <option key={t.id} value={t.id}>{t.name}{t.active ? '' : ' (Inactive)'}</option>)}</select></label>{state.data?.balances?.filter(t => t.id === typeId).map(t => <p key={t.id} className="rounded-xl bg-slate-50 p-3 text-xs text-slate-600">Allocated {t.allocated} · Used {t.used} · Reserved {t.reserved} · Available {t.available}</p>)}<label className={label}>Total annual days<input required type="number" min="0" max="366" step="0.5" className={field} value={units} onChange={e => setUnits(e.target.value)}/></label><label className={label}>Adjustment reason<textarea required minLength={3} maxLength={1000} className={field} value={reason} onChange={e => setReason(e.target.value)}/></label><button className={button} disabled={busy || !state.data}>Save allocation</button></fieldset><Notice error>{error || state.error}</Notice>{state.data?.adjustments?.length > 0 && <details className="lg:col-span-2"><summary className="cursor-pointer text-sm font-semibold text-slate-700">Recent allocation history</summary><div className="mt-3 space-y-2">{state.data.adjustments.map(a => <div key={a._id} className="rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><p>{state.data.balances.find(t => t.id === a.typeId)?.name || 'Leave'} · {a.before} → {a.after} days</p><p className="mt-1 whitespace-pre-wrap">{a.reason}</p><p className="mt-1 text-slate-400">{new Date(a.at).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST</p></div>)}</div></details>}</form>;
}
